# SPDX-License-Identifier: GPL-2.0
root_require

# Check that monitoring `debug' topic doesn't end up looping endlessly on the
# debug messages generated by the monitor stream itself. Attach a monitor, issue
# an RPC, and check whether an inordinate number of debug lines was generated as
# a response.

Bbdd_setup_ns NS1
in_ns NS1

Bbdd_setup_socket SD1
with_socket SD1
adf_Bbdd_start

monout="${tmpdir}/monout"
with_socket SD1 Bbdd_bground monitor debug > "$monout"
monitor_pid=$!

sleep 0.2 # Let the subscription land.

with_socket SD1 Bbdd -q echo > /dev/null

sleep 1 # Long enough for a feedback loop to produce many messages.

kill_process "$monitor_pid"

n=$(wc -l < "$monout")
((n < 50))
check_err $? "$n debug notifications for one request, < 50 expected"
Bbdd_log_test "debug monitor doesn't feed back on its own notifications"
